In [59]:
%run ./packer.ipynb

In [223]:
packer = Packer()

# packer.add_bin(Bin('small-envelope', 11.5, 6.125, 0.25, 10))
# packer.add_bin(Bin('large-envelope', 15.0, 12.0, 0.75, 15))
# packer.add_bin(Bin('small-box', 8.625, 5.375, 1.625, 70.0))
# packer.add_bin(Bin('medium-box', 11.0, 8.5, 5.5, 70.0))
# packer.add_bin(Bin('medium-2-box', 13.625, 11.875, 3.375, 70.0))
# packer.add_bin(Bin('large-box', 8, 6, 4, 300))

room_l = 20
room_w = 15
room_h = 10
room_weight = 500 

packer.add_bin(Bin('large-2-box', room_l, room_w, room_h, room_weight))

packer.add_item(Item('size-xs', 3, 2, 1, 5))
packer.add_item(Item('size-xs', 3, 2, 1, 5))
packer.add_item(Item('size-xs', 3, 2, 1, 5))
packer.add_item(Item('size-xs', 3, 2, 1, 5))
packer.add_item(Item('size-xs', 3, 2, 1, 5))
packer.add_item(Item('size-xs', 3, 2, 1, 5))

packer.add_item(Item('size-s', 5, 3, 2, 10))
packer.add_item(Item('size-s', 5, 3, 2, 10))
packer.add_item(Item('size-s', 5, 3, 2, 10))
packer.add_item(Item('size-s', 5, 3, 2, 10))
packer.add_item(Item('size-s', 5, 3, 2, 10))
packer.add_item(Item('size-s', 5, 3, 2, 10))
packer.add_item(Item('size-s', 5, 3, 2, 10))
packer.add_item(Item('size-s', 5, 3, 2, 10))

packer.add_item(Item('size-m', 6, 4, 2, 25))
packer.add_item(Item('size-m', 6, 4, 2, 25))
packer.add_item(Item('size-m', 6, 4, 2, 25))
packer.add_item(Item('size-m', 6, 4, 2, 25))

packer.add_item(Item('size-l', 7, 5, 3, 35))

packer.pack()

::::::::::: large-2-box(20.000x15.000x10.000, max_weight:500.000) vol(3000.000) item_number(19) filling_ratio(0.191)
FITTED ITEMS:
====>  7.000,5.000,3.000,35.000,[0, 0, 0],2
====>  6.000,4.000,2.000,25.000,[Decimal('3.000'), 0, 0],2
====>  6.000,4.000,2.000,25.000,[Decimal('5.000'), 0, 0],2
====>  6.000,4.000,2.000,25.000,[0, Decimal('5.000'), 0],1
====>  6.000,4.000,2.000,25.000,[Decimal('7.000'), 0, 0],3
====>  5.000,3.000,2.000,10.000,[0, 0, Decimal('7.000')],1
====>  5.000,3.000,2.000,10.000,[Decimal('11.000'), 0, 0],5
====>  5.000,3.000,2.000,10.000,[0, Decimal('11.000'), 0],2
====>  5.000,3.000,2.000,10.000,[Decimal('16.000'), 0, 0],3
====>  5.000,3.000,2.000,10.000,[Decimal('2.000'), Decimal('5.000'), 0],1
====>  5.000,3.000,2.000,10.000,[Decimal('2.000'), 0, Decimal('7.000')],1
====>  5.000,3.000,2.000,10.000,[Decimal('7.000'), Decimal('2.000'), 0],2
====>  5.000,3.000,2.000,10.000,[Decimal('9.000'), Decimal('2.000'), 0],3
====>  3.000,2.000,1.000,5.000,[0, Decimal('14.000'), 0],3
====>  3.000,2.000,1.000,5.000,[Decimal('19.000'), 0, 0],2
====>  3.000,2.000,1.000,5.000,[Decimal('2.000'), Decimal('10.000'), 0],1
====>  3.000,2.000,1.000,5.000,[Decimal('2.000'), Decimal('10.000'), Decimal('2.000')],1
====>  3.000,2.000,1.000,5.000,[Decimal('12.000'), Decimal('2.000'), 0],5
====>  3.000,2.000,1.000,5.000,[Decimal('12.000'), Decimal('2.000'), Decimal('2.000')],3

UNFITTED ITEMS:

In [224]:
packer.item_strings

['7.000,5.000,3.000,35.000,[0, 0, 0],2',
 "6.000,4.000,2.000,25.000,[Decimal('3.000'), 0, 0],2",
 "6.000,4.000,2.000,25.000,[Decimal('5.000'), 0, 0],2",
 "6.000,4.000,2.000,25.000,[0, Decimal('5.000'), 0],1",
 "6.000,4.000,2.000,25.000,[Decimal('7.000'), 0, 0],3",
 "5.000,3.000,2.000,10.000,[0, 0, Decimal('7.000')],1",
 "5.000,3.000,2.000,10.000,[Decimal('11.000'), 0, 0],5",
 "5.000,3.000,2.000,10.000,[0, Decimal('11.000'), 0],2",
 "5.000,3.000,2.000,10.000,[Decimal('16.000'), 0, 0],3",
 "5.000,3.000,2.000,10.000,[Decimal('2.000'), Decimal('5.000'), 0],1",
 "5.000,3.000,2.000,10.000,[Decimal('2.000'), 0, Decimal('7.000')],1",
 "5.000,3.000,2.000,10.000,[Decimal('7.000'), Decimal('2.000'), 0],2",
 "5.000,3.000,2.000,10.000,[Decimal('9.000'), Decimal('2.000'), 0],3",
 "3.000,2.000,1.000,5.000,[0, Decimal('14.000'), 0],3",
 "3.000,2.000,1.000,5.000,[Decimal('19.000'), 0, 0],2",
 "3.000,2.000,1.000,5.000,[Decimal('2.000'), Decimal('10.000'), 0],1",
 "3.000,2.000,1.000,5.000,[Decimal('2.000'), Decimal('10.000'), Decimal('2.000')],1",
 "3.000,2.000,1.000,5.000,[Decimal('12.000'), Decimal('2.000'), 0],5",
 "3.000,2.000,1.000,5.000,[Decimal('12.000'), Decimal('2.000'), Decimal('2.000')],3"]

In [225]:
import numpy as np
import pandas as pd# Update default settings to show 2 decimal place

column_names = ["x","y","z","weight", "l", "w","h","rotation"]
df = pd.DataFrame(columns = column_names)

In [226]:
df

Empty DataFrame
Columns: [x, y, z, weight, l, w, h, rotation]
Index: []

In [227]:
for item in packer.item_strings:
    item_charac = item.split(",")
    print(item_charac)
    df2 = {'l': item_charac[0], 'w': item_charac[1], 'h': item_charac[2], 'weight': item_charac[3],'x': item_charac[4],'y': item_charac[5],'z': item_charac[6],'rotation': item_charac[7]}
    df = df.append(df2, ignore_index = True)

['7.000', '5.000', '3.000', '35.000', '[0', ' 0', ' 0]', '2']
['6.000', '4.000', '2.000', '25.000', "[Decimal('3.000')", ' 0', ' 0]', '2']
['6.000', '4.000', '2.000', '25.000', "[Decimal('5.000')", ' 0', ' 0]', '2']
['6.000', '4.000', '2.000', '25.000', '[0', " Decimal('5.000')", ' 0]', '1']
['6.000', '4.000', '2.000', '25.000', "[Decimal('7.000')", ' 0', ' 0]', '3']
['5.000', '3.000', '2.000', '10.000', '[0', ' 0', " Decimal('7.000')]", '1']
['5.000', '3.000', '2.000', '10.000', "[Decimal('11.000')", ' 0', ' 0]', '5']
['5.000', '3.000', '2.000', '10.000', '[0', " Decimal('11.000')", ' 0]', '2']
['5.000', '3.000', '2.000', '10.000', "[Decimal('16.000')", ' 0', ' 0]', '3']
['5.000', '3.000', '2.000', '10.000', "[Decimal('2.000')", " Decimal('5.000')", ' 0]', '1']
['5.000', '3.000', '2.000', '10.000', "[Decimal('2.000')", ' 0', " Decimal('7.000')]", '1']
['5.000', '3.000', '2.000', '10.000', "[Decimal('7.000')", " Decimal('2.000')", ' 0]', '2']
['5.000', '3.000', '2.000', '10.000', "[Decimal('9.000')", " Decimal('2.000')", ' 0]', '3']
['3.000', '2.000', '1.000', '5.000', '[0', " Decimal('14.000')", ' 0]', '3']
['3.000', '2.000', '1.000', '5.000', "[Decimal('19.000')", ' 0', ' 0]', '2']
['3.000', '2.000', '1.000', '5.000', "[Decimal('2.000')", " Decimal('10.000')", ' 0]', '1']
['3.000', '2.000', '1.000', '5.000', "[Decimal('2.000')", " Decimal('10.000')", " Decimal('2.000')]", '1']
['3.000', '2.000', '1.000', '5.000', "[Decimal('12.000')", " Decimal('2.000')", ' 0]', '5']
['3.000', '2.000', '1.000', '5.000', "[Decimal('12.000')", " Decimal('2.000')", " Decimal('2.000')]", '3']

In [228]:
df

,x,y,z,weight,l,w,h,rotation
0,[0,0,0],35.000,7.000,5.000,3.000,2
1,[Decimal('3.000'),0,0],25.000,6.000,4.000,2.000,2
2,[Decimal('5.000'),0,0],25.000,6.000,4.000,2.000,2
3,[0,Decimal('5.000'),0],25.000,6.000,4.000,2.000,1
4,[Decimal('7.000'),0,0],25.000,6.000,4.000,2.000,3
5,[0,0,Decimal('7.000')],10.000,5.000,3.000,2.000,1
6,[Decimal('11.000'),0,0],10.000,5.000,3.000,2.000,5
7,[0,Decimal('11.000'),0],10.000,5.000,3.000,2.000,2
8,[Decimal('16.000'),0,0],10.000,5.000,3.000,2.000,3
9,[Decimal('2.000'),Decimal('5.000'),0],10.000,5.000,3.000,2.000,1
10,[Decimal('2.000'),0,Decimal('7.000')],10.000,5.000,3.000,2.000,1
11,[Decimal('7.000'),Decimal('2.000'),0],10.000,5.000,3.000,2.000,2
12,[Decimal('9.000'),Decimal('2.000'),0],10.000,5.000,3.000,2.000,3
13,[0,Decimal('14.000'),0],5.000,3.000,2.000,1.000,3
14,[Decimal('19.000'),0,0],5.000,3.000,2.000,1.000,2
15,[Decimal('2.000'),Decimal('10.000'),0],5.000,3.000,2.000,1.000,1
16,[Decimal('2.000'),Decimal('10.000'),Decimal('2.000')],5.000,3.000,2.000,1.000,1
17,[Decimal('12.000'),Decimal('2.000'),0],5.000,3.000,2.000,1.000,5
18,[Decimal('12.000'),Decimal('2.000'),Decimal('2.000')],5.000,3.000,2.000,1.000,3

In [229]:
df["x"] = df["x"].str.replace("Decimal","")
df["x"] = df["x"].str.replace("[","")
df["x"] = df["x"].str.replace("(","")
df["x"] = df["x"].str.replace(")","")
df["x"] = df["x"].str.replace("'","")

df["y"] = df["y"].str.replace("Decimal","")
df["y"] = df["y"].str.replace("[","")
df["y"] = df["y"].str.replace("(","")
df["y"] = df["y"].str.replace(")","")
df["y"] = df["y"].str.replace("'","")

df["z"] = df["z"].str.replace("Decimal","")
df["z"] = df["z"].str.replace("]","")
df["z"] = df["z"].str.replace("(","")
df["z"] = df["z"].str.replace(")","")
df["z"] = df["z"].str.replace("'","")

In [230]:
df = df.astype(np.float).astype(np.int64)

In [231]:
df

     x   y  z  weight  l  w  h  rotation
0    0   0  0      35  7  5  3         2
1    3   0  0      25  6  4  2         2
2    5   0  0      25  6  4  2         2
3    0   5  0      25  6  4  2         1
4    7   0  0      25  6  4  2         3
5    0   0  7      10  5  3  2         1
6   11   0  0      10  5  3  2         5
7    0  11  0      10  5  3  2         2
8   16   0  0      10  5  3  2         3
9    2   5  0      10  5  3  2         1
10   2   0  7      10  5  3  2         1
11   7   2  0      10  5  3  2         2
12   9   2  0      10  5  3  2         3
13   0  14  0       5  3  2  1         3
14  19   0  0       5  3  2  1         2
15   2  10  0       5  3  2  1         1
16   2  10  2       5  3  2  1         1
17  12   2  0       5  3  2  1         5
18  12   2  2       5  3  2  1         3

In [232]:
# df.to_csv('/Users/macos/heineken_projects/optimize-storage-space/Measuring-Size-of-Objects-with-OpenCV/csv/packing-result.csv')

In [233]:
cuboid_str = []

In [234]:
for ind in df.index:
    i = df['rotation'][ind]
    x = df['x'][ind]
    y = df['y'][ind]
    z = df['z'][ind]
    
    l = df['l'][ind]
    w = df['w'][ind]
    h = df['h'][ind]
    
    if i == 0:
        a = l
        b = w
        c = h
    elif i == 1:
        a = w
        b = l
        c = h
    elif i == 2:
        a = h
        b = w
        c = l
    elif i == 3:
        a = w
        b = h
        c = l
    elif i == 4:
        a = h
        b = l
        c = w
    elif i == 5:
        a = l
        b = h
        c = w
        
    print(x,y,z,a,b,c)
    
    str_cube = x,y,z,a,b,c
    cuboid_str.append(str_cube)

0 0 0 3 5 7
3 0 0 2 4 6
5 0 0 2 4 6
0 5 0 4 6 2
7 0 0 4 2 6
0 0 7 3 5 2
11 0 0 5 2 3
0 11 0 2 3 5
16 0 0 3 2 5
2 5 0 3 5 2
2 0 7 3 5 2
7 2 0 2 3 5
9 2 0 3 2 5
0 14 0 2 1 3
19 0 0 1 2 3
2 10 0 2 3 1
2 10 2 2 3 1
12 2 0 3 1 2
12 2 2 2 1 3

In [235]:
cuboid_2 = []

In [ ]:
room_l = 20
room_w = 15
room_h = 10
room_weight = 500

In [248]:
for s in cuboid_str:
    new_s = 'cuboid' + str(s)
    cuboid_2.append(new_s)
room_str = 'cuboid(' + '0,0,0' + ", "+ str(room_l)+ ", "+ str(room_w)+ ", "+ str(room_h) + ')'
cuboid_2.append(room_str)

In [249]:
cuboid_2

['cuboid(0, 0, 0, 3, 5, 7)',
 'cuboid(3, 0, 0, 2, 4, 6)',
 'cuboid(5, 0, 0, 2, 4, 6)',
 'cuboid(0, 5, 0, 4, 6, 2)',
 'cuboid(7, 0, 0, 4, 2, 6)',
 'cuboid(0, 0, 7, 3, 5, 2)',
 'cuboid(11, 0, 0, 5, 2, 3)',
 'cuboid(0, 11, 0, 2, 3, 5)',
 'cuboid(16, 0, 0, 3, 2, 5)',
 'cuboid(2, 5, 0, 3, 5, 2)',
 'cuboid(2, 0, 7, 3, 5, 2)',
 'cuboid(7, 2, 0, 2, 3, 5)',
 'cuboid(9, 2, 0, 3, 2, 5)',
 'cuboid(0, 14, 0, 2, 1, 3)',
 'cuboid(19, 0, 0, 1, 2, 3)',
 'cuboid(2, 10, 0, 2, 3, 1)',
 'cuboid(2, 10, 2, 2, 3, 1)',
 'cuboid(12, 2, 0, 3, 1, 2)',
 'cuboid(12, 2, 2, 2, 1, 3)',
 'cuboid(0, 0, 0, 3, 5, 7)',
 'cuboid(3, 0, 0, 2, 4, 6)',
 'cuboid(5, 0, 0, 2, 4, 6)',
 'cuboid(0, 5, 0, 4, 6, 2)',
 'cuboid(7, 0, 0, 4, 2, 6)',
 'cuboid(0, 0, 7, 3, 5, 2)',
 'cuboid(11, 0, 0, 5, 2, 3)',
 'cuboid(0, 11, 0, 2, 3, 5)',
 'cuboid(16, 0, 0, 3, 2, 5)',
 'cuboid(2, 5, 0, 3, 5, 2)',
 'cuboid(2, 0, 7, 3, 5, 2)',
 'cuboid(7, 2, 0, 2, 3, 5)',
 'cuboid(9, 2, 0, 3, 2, 5)',
 'cuboid(0, 14, 0, 2, 1, 3)',
 'cuboid(19, 0, 0, 1, 2, 3)',
 'cuboid(2, 10, 0, 2, 3, 1)',
 'cuboid(2, 10, 2, 2, 3, 1)',
 'cuboid(12, 2, 0, 3, 1, 2)',
 'cuboid(12, 2, 2, 2, 1, 3)',
 'cuboid(0, 0, 0, 3, 5, 7)',
 'cuboid(3, 0, 0, 2, 4, 6)',
 'cuboid(5, 0, 0, 2, 4, 6)',
 'cuboid(0, 5, 0, 4, 6, 2)',
 'cuboid(7, 0, 0, 4, 2, 6)',
 'cuboid(0, 0, 7, 3, 5, 2)',
 'cuboid(11, 0, 0, 5, 2, 3)',
 'cuboid(0, 11, 0, 2, 3, 5)',
 'cuboid(16, 0, 0, 3, 2, 5)',
 'cuboid(2, 5, 0, 3, 5, 2)',
 'cuboid(2, 0, 7, 3, 5, 2)',
 'cuboid(7, 2, 0, 2, 3, 5)',
 'cuboid(9, 2, 0, 3, 2, 5)',
 'cuboid(0, 14, 0, 2, 1, 3)',
 'cuboid(19, 0, 0, 1, 2, 3)',
 'cuboid(2, 10, 0, 2, 3, 1)',
 'cuboid(2, 10, 2, 2, 3, 1)',
 'cuboid(12, 2, 0, 3, 1, 2)',
 'cuboid(12, 2, 2, 2, 1, 3)',
 'cuboid0,0,0201510',
 'cuboid(0, 0, 0, 3, 5, 7)',
 'cuboid(3, 0, 0, 2, 4, 6)',
 'cuboid(5, 0, 0, 2, 4, 6)',
 'cuboid(0, 5, 0, 4, 6, 2)',
 'cuboid(7, 0, 0, 4, 2, 6)',
 'cuboid(0, 0, 7, 3, 5, 2)',
 'cuboid(11, 0, 0, 5, 2, 3)',
 'cuboid(0, 11, 0, 2, 3, 5)',
 'cuboid(16, 0, 0, 3, 2, 5)',
 'cuboid(2, 5, 0, 3, 5, 2)',
 'cuboid(2, 0, 7, 3, 5, 2)',
 'cuboid(7, 2, 0, 2, 3, 5)',
 'cuboid(9, 2, 0, 3, 2, 5)',
 'cuboid(0, 14, 0, 2, 1, 3)',
 'cuboid(19, 0, 0, 1, 2, 3)',
 'cuboid(2, 10, 0, 2, 3, 1)',
 'cuboid(2, 10, 2, 2, 3, 1)',
 'cuboid(12, 2, 0, 3, 1, 2)',
 'cuboid(12, 2, 2, 2, 1, 3)',
 'cuboid(0,0,0 20 15 10',
 'cuboid(0, 0, 0, 3, 5, 7)',
 'cuboid(3, 0, 0, 2, 4, 6)',
 'cuboid(5, 0, 0, 2, 4, 6)',
 'cuboid(0, 5, 0, 4, 6, 2)',
 'cuboid(7, 0, 0, 4, 2, 6)',
 'cuboid(0, 0, 7, 3, 5, 2)',
 'cuboid(11, 0, 0, 5, 2, 3)',
 'cuboid(0, 11, 0, 2, 3, 5)',
 'cuboid(16, 0, 0, 3, 2, 5)',
 'cuboid(2, 5, 0, 3, 5, 2)',
 'cuboid(2, 0, 7, 3, 5, 2)',
 'cuboid(7, 2, 0, 2, 3, 5)',
 'cuboid(9, 2, 0, 3, 2, 5)',
 'cuboid(0, 14, 0, 2, 1, 3)',
 'cuboid(19, 0, 0, 1, 2, 3)',
 'cuboid(2, 10, 0, 2, 3, 1)',
 'cuboid(2, 10, 2, 2, 3, 1)',
 'cuboid(12, 2, 0, 3, 1, 2)',
 'cuboid(12, 2, 2, 2, 1, 3)',
 'cuboid(0,0,0 20 15 10)',
 'cuboid(0, 0, 0, 3, 5, 7)',
 'cuboid(3, 0, 0, 2, 4, 6)',
 'cuboid(5, 0, 0, 2, 4, 6)',
 'cuboid(0, 5, 0, 4, 6, 2)',
 'cuboid(7, 0, 0, 4, 2, 6)',
 'cuboid(0, 0, 7, 3, 5, 2)',
 'cuboid(11, 0, 0, 5, 2, 3)',
 'cuboid(0, 11, 0, 2, 3, 5)',
 'cuboid(16, 0, 0, 3, 2, 5)',
 'cuboid(2, 5, 0, 3, 5, 2)',
 'cuboid(2, 0, 7, 3, 5, 2)',
 'cuboid(7, 2, 0, 2, 3, 5)',
 'cuboid(9, 2, 0, 3, 2, 5)',
 'cuboid(0, 14, 0, 2, 1, 3)',
 'cuboid(19, 0, 0, 1, 2, 3)',
 'cuboid(2, 10, 0, 2, 3, 1)',
 'cuboid(2, 10, 2, 2, 3, 1)',
 'cuboid(12, 2, 0, 3, 1, 2)',
 'cuboid(12, 2, 2, 2, 1, 3)',
 'cuboid(0,0,0, 20, 15, 10)']

In [250]:
s = '\n'.join(str(x) for x in cuboid_2)

In [251]:
print(s)

cuboid(0, 0, 0, 3, 5, 7)
cuboid(3, 0, 0, 2, 4, 6)
cuboid(5, 0, 0, 2, 4, 6)
cuboid(0, 5, 0, 4, 6, 2)
cuboid(7, 0, 0, 4, 2, 6)
cuboid(0, 0, 7, 3, 5, 2)
cuboid(11, 0, 0, 5, 2, 3)
cuboid(0, 11, 0, 2, 3, 5)
cuboid(16, 0, 0, 3, 2, 5)
cuboid(2, 5, 0, 3, 5, 2)
cuboid(2, 0, 7, 3, 5, 2)
cuboid(7, 2, 0, 2, 3, 5)
cuboid(9, 2, 0, 3, 2, 5)
cuboid(0, 14, 0, 2, 1, 3)
cuboid(19, 0, 0, 1, 2, 3)
cuboid(2, 10, 0, 2, 3, 1)
cuboid(2, 10, 2, 2, 3, 1)
cuboid(12, 2, 0, 3, 1, 2)
cuboid(12, 2, 2, 2, 1, 3)
cuboid(0, 0, 0, 3, 5, 7)
cuboid(3, 0, 0, 2, 4, 6)
cuboid(5, 0, 0, 2, 4, 6)
cuboid(0, 5, 0, 4, 6, 2)
cuboid(7, 0, 0, 4, 2, 6)
cuboid(0, 0, 7, 3, 5, 2)
cuboid(11, 0, 0, 5, 2, 3)
cuboid(0, 11, 0, 2, 3, 5)
cuboid(16, 0, 0, 3, 2, 5)
cuboid(2, 5, 0, 3, 5, 2)
cuboid(2, 0, 7, 3, 5, 2)
cuboid(7, 2, 0, 2, 3, 5)
cuboid(9, 2, 0, 3, 2, 5)
cuboid(0, 14, 0, 2, 1, 3)
cuboid(19, 0, 0, 1, 2, 3)
cuboid(2, 10, 0, 2, 3, 1)
cuboid(2, 10, 2, 2, 3, 1)
cuboid(12, 2, 0, 3, 1, 2)
cuboid(12, 2, 2, 2, 1, 3)
cuboid(0, 0, 0, 3, 5, 7)
cuboid(3, 0, 0, 2, 4, 6)
cuboid(5, 0, 0, 2, 4, 6)
cuboid(0, 5, 0, 4, 6, 2)
cuboid(7, 0, 0, 4, 2, 6)
cuboid(0, 0, 7, 3, 5, 2)
cuboid(11, 0, 0, 5, 2, 3)
cuboid(0, 11, 0, 2, 3, 5)
cuboid(16, 0, 0, 3, 2, 5)
cuboid(2, 5, 0, 3, 5, 2)
cuboid(2, 0, 7, 3, 5, 2)
cuboid(7, 2, 0, 2, 3, 5)
cuboid(9, 2, 0, 3, 2, 5)
cuboid(0, 14, 0, 2, 1, 3)
cuboid(19, 0, 0, 1, 2, 3)
cuboid(2, 10, 0, 2, 3, 1)
cuboid(2, 10, 2, 2, 3, 1)
cuboid(12, 2, 0, 3, 1, 2)
cuboid(12, 2, 2, 2, 1, 3)
cuboid0,0,0201510
cuboid(0, 0, 0, 3, 5, 7)
cuboid(3, 0, 0, 2, 4, 6)
cuboid(5, 0, 0, 2, 4, 6)
cuboid(0, 5, 0, 4, 6, 2)
cuboid(7, 0, 0, 4, 2, 6)
cuboid(0, 0, 7, 3, 5, 2)
cuboid(11, 0, 0, 5, 2, 3)
cuboid(0, 11, 0, 2, 3, 5)
cuboid(16, 0, 0, 3, 2, 5)
cuboid(2, 5, 0, 3, 5, 2)
cuboid(2, 0, 7, 3, 5, 2)
cuboid(7, 2, 0, 2, 3, 5)
cuboid(9, 2, 0, 3, 2, 5)
cuboid(0, 14, 0, 2, 1, 3)
cuboid(19, 0, 0, 1, 2, 3)
cuboid(2, 10, 0, 2, 3, 1)
cuboid(2, 10, 2, 2, 3, 1)
cuboid(12, 2, 0, 3, 1, 2)
cuboid(12, 2, 2, 2, 1, 3)
cuboid(0,0,0 20 15 10
cuboid(0, 0, 0, 3, 5, 7)
cuboid(3, 0, 0, 2, 4, 6)
cuboid(5, 0, 0, 2, 4, 6)
cuboid(0, 5, 0, 4, 6, 2)
cuboid(7, 0, 0, 4, 2, 6)
cuboid(0, 0, 7, 3, 5, 2)
cuboid(11, 0, 0, 5, 2, 3)
cuboid(0, 11, 0, 2, 3, 5)
cuboid(16, 0, 0, 3, 2, 5)
cuboid(2, 5, 0, 3, 5, 2)
cuboid(2, 0, 7, 3, 5, 2)
cuboid(7, 2, 0, 2, 3, 5)
cuboid(9, 2, 0, 3, 2, 5)
cuboid(0, 14, 0, 2, 1, 3)
cuboid(19, 0, 0, 1, 2, 3)
cuboid(2, 10, 0, 2, 3, 1)
cuboid(2, 10, 2, 2, 3, 1)
cuboid(12, 2, 0, 3, 1, 2)
cuboid(12, 2, 2, 2, 1, 3)
cuboid(0,0,0 20 15 10)
cuboid(0, 0, 0, 3, 5, 7)
cuboid(3, 0, 0, 2, 4, 6)
cuboid(5, 0, 0, 2, 4, 6)
cuboid(0, 5, 0, 4, 6, 2)
cuboid(7, 0, 0, 4, 2, 6)
cuboid(0, 0, 7, 3, 5, 2)
cuboid(11, 0, 0, 5, 2, 3)
cuboid(0, 11, 0, 2, 3, 5)
cuboid(16, 0, 0, 3, 2, 5)
cuboid(2, 5, 0, 3, 5, 2)
cuboid(2, 0, 7, 3, 5, 2)
cuboid(7, 2, 0, 2, 3, 5)
cuboid(9, 2, 0, 3, 2, 5)
cuboid(0, 14, 0, 2, 1, 3)
cuboid(19, 0, 0, 1, 2, 3)
cuboid(2, 10, 0, 2, 3, 1)
cuboid(2, 10, 2, 2, 3, 1)
cuboid(12, 2, 0, 3, 1, 2)
cuboid(12, 2, 2, 2, 1, 3)
cuboid(0,0,0, 20, 15, 10)